@startuml
title SCARA Robot Pick-and-Place State Machine
skinparam state {
  RoundCorner 20
  BackgroundColor #F1F8E9
  BorderColor #2E7D32
}
[*] --> Idle : System Start
Idle : state = -1
Idle : target_obj = None

state "Detection" as State0 {
    State0 : state = 0
    State0 : Move to Object XY
    State0 : Z-axis = 0.06 (Safety Height)
}

state "Descending" as State1 {
    State1 : state = 1
    State1 : data.ctrl[2] = -0.2 (Down)
}

state "Grasping" as State2 {
    State2 : state = 2
    State2 : vacuum_on = True
}

state "Lifting" as State3 {
    State3 : state = 3
    State3 : data.ctrl[2] = 0.06 (Up)
}

state "Moving to Goal" as State4 {
    State4 : state = 4
    State4 : Move to Goal XY
}

state "Releasing" as State5 {
    State5 : state = 5
    State5 : data.ctrl[2] = -0.06 (Lower to Goal)
    State5 : vacuum_on = False
}

state "Reset Environment" as State6 {
    State6 : state = 6
    State6 : Randomize Object Pos & Color
}

Idle -right-> State0 : Results detected \n& time > release_time
State0 -right-> State1 : Distance XY < 0.01m
State1 -right-> State2 : Distance Z < 0.022m
State2 --> State3 : Instant transition
State3 -left-> State4 : Joint 3 (Z) > 0.05m
State4 -left-> State5 : Distance to Goal < 0.01m
State5 -left-> State6 : Time > 0.2s
State6 -up-> Idle : Time > 0.5s

@enduml